package com.logicbig.example;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	/***
	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam Integer id, @RequestParam Integer psw, @RequestParam Integer salt, @RequestParam String name
			, @RequestParam String username) {
		 //@ResponseBody means the returned String is the response, not a view name
		 //@RequestParam means it is a parameter from the GET or POST request
		
		//Person n = new Person();
		//n.setName(name);
		//n.setEmail(email);
		//userRepository.save(n);
		//return "Saved";
		
		Person person = new Person();
        person.setId(id);
        person.setPsw(psw);
        person.setSalt(salt);
        person.setName(name);
        person.setUsername(username);
        return "Saved";
	}
	
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<Person> getAllPersons() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
	
	**/
	
}
